---

# example test (check) run:
# ansible-playbook translate_terraform.yml -i inventory/tf-vpc-euc1/ --check -v --tags ec2_eip --step

- hosts: localhost
  connection: local
  vars:
    regions: [ 'eu-central-1' ]
#    regions: [ 'eu-central-1', 'eu-west-1' ]
  tasks:

    - include: "{{ item }}/tasks/ec2_vpc_route_table.yml"
      with_items: "{{ regions }}"
      tags: ec2_vpc_route_table

    - include: "{{ item }}/tasks/ec2_group.yml"
      with_items: "{{ regions }}"
      tags: ec2_group

    - include: "{{ item }}/tasks/ec2_eip.yml"
      with_items: "{{ regions }}"
      tags: ec2_eip

    - include: "{{ item }}/tasks/route53_zone.yml"
      with_items: "{{ regions }}"
      tags: route53_zone

    - include: "{{ item }}/tasks/route53.yml"
      with_items: "{{ regions }}"
      tags: route53

    - include: "{{ item }}/tasks/ec2_elb_lb.yml"
      with_items: "{{ regions }}"
      tags: ec2_elb_lb

    - include: "{{ item }}/tasks/rds.yml"
      with_items: "{{ regions }}"
      tags: rds

    - include: "{{ item }}/tasks/rds_subnet_group.yml"
      with_items: "{{ regions }}"
      tags: rds_subnet_group

    - include: "{{ item }}/tasks/rds_param_group.yml"
      with_items: "{{ regions }}"
      tags: rds_param_group

    - include: "{{ item }}/tasks/iam.yml"
      with_items: "{{ regions }}"
      tags: iam

    - include: "{{ item }}/tasks/iam_role.yml"
      with_items: "{{ regions }}"
      tags: iam_role

    - include: "{{ item }}/tasks/sns_topic.yml"
      with_items: "{{ regions }}"
      tags: sns_topic

    - include: "{{ item }}/tasks/s3.yml"
      with_items: "{{ regions }}"
      tags: s3

# foreach ansible module
# add lines to translate_terraform.yml (this file)
# add lines to create-ansible-tasks.py
# add jinja template
